name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy_to_firebase:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

      - name: Deploy to Firebase
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Authenticate with Firebase
        run: firebase login:ci --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARLOSROJAS_DEV }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARLOSROJAS_DEV }}'
          channelId: live
          projectId: lealtad-club # Replace with your Firebase project ID